#!/bin/bash

export PROJECT_NAME="Kris Kringle"
export ITERMOCIL_TASKS=("edit" "indexgen-watch")
export ESLINT_PATHS=("$SRC")

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0
