#!/bin/bash
  
. ./task-vars

README="README.md"

node \
--experimental-specifier-resolution=node \ # The node mode enables support for optional file extensions and the ability to import a directory that has an index file.
./tasks/lib/readme-file-generator.mjs > $README # The mjs extension enables the ES module loader.

npx doctoc --maxlevel 2 $README
