#!/bin/bash

./tasks/itermocil-install

cat > "iTermocil.yml" <<EOF
windows:
  - name: $PROJECT_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
      - commands:
        - nvm use
        - clear
        - code .
      - commands:
        - nvm use
        - clear
        - ./task indexgen-watch
EOF

itermocil
